ALLOWED_TRANSITIONS = {
    "INGESTED": ["EXTRACTING"],
    "EXTRACTING": ["EXTRACTED"],
    "EXTRACTED": ["REVIEW_PENDING"],
    "REVIEW_PENDING": ["APPROVAL_PENDING"],
    "APPROVAL_PENDING": ["APPROVED", "REJECTED"],
    "APPROVED": ["ARCHIVED"],
}
