"""create documents and textract_jobs

Revision ID: 21836ea583d2
Revises: 
Create Date: 2025-11-04 17:37:58.124680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21836ea583d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s3_bucket', sa.String(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_s3_key'), 'documents', ['s3_key'], unique=False)
    op.create_table('textract_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('feature_types', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_textract_jobs_job_id'), 'textract_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_textract_jobs_status'), 'textract_jobs', ['status'], unique=False)
    op.create_table('key_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('key_text', sa.Text(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('key_confidence', sa.Float(), nullable=True),
    sa.Column('value_confidence', sa.Float(), nullable=True),
    sa.Column('key_bbox', sa.JSON(), nullable=True),
    sa.Column('value_bbox', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['textract_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_key_values_document_id'), 'key_values', ['document_id'], unique=False)
    op.create_index(op.f('ix_key_values_job_id'), 'key_values', ['job_id'], unique=False)
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('footer', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['textract_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tables_document_id'), 'tables', ['document_id'], unique=False)
    op.create_index(op.f('ix_tables_job_id'), 'tables', ['job_id'], unique=False)
    op.create_table('textract_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['textract_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('table_cells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('col_index', sa.Integer(), nullable=True),
    sa.Column('row_span', sa.Integer(), nullable=True),
    sa.Column('col_span', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_cells_table_id'), 'table_cells', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_cells_table_id'), table_name='table_cells')
    op.drop_table('table_cells')
    op.drop_table('textract_raw')
    op.drop_index(op.f('ix_tables_job_id'), table_name='tables')
    op.drop_index(op.f('ix_tables_document_id'), table_name='tables')
    op.drop_table('tables')
    op.drop_index(op.f('ix_key_values_job_id'), table_name='key_values')
    op.drop_index(op.f('ix_key_values_document_id'), table_name='key_values')
    op.drop_table('key_values')
    op.drop_index(op.f('ix_textract_jobs_status'), table_name='textract_jobs')
    op.drop_index(op.f('ix_textract_jobs_job_id'), table_name='textract_jobs')
    op.drop_table('textract_jobs')
    op.drop_index(op.f('ix_documents_s3_key'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
