"""correct_add_columns

Revision ID: 872aec5f46a7
Revises: 669fdb67233c
Create Date: 2026-02-20 13:30:37.805423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872aec5f46a7'
down_revision: Union[str, Sequence[str], None] = '669fdb67233c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_lifecycle', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('documents', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('archived_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('documents', 'archived_at')
    op.drop_column('documents', 'deleted_at')
    op.alter_column('document_lifecycle', 'document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
