"""add_approval_fields

Revision ID: bc661fece23a
Revises: 872aec5f46a7
Create Date: 2026-02-20 18:39:59.172782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc661fece23a'
down_revision: Union[str, Sequence[str], None] = '872aec5f46a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('reviewer_notes', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('approver_notes', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('documents', sa.Column('risk_indicators', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('digitally_signed_by', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('digitally_signed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'digitally_signed_at')
    op.drop_column('documents', 'digitally_signed_by')
    op.drop_column('documents', 'risk_indicators')
    op.drop_column('documents', 'risk_score')
    op.drop_column('documents', 'approver_notes')
    op.drop_column('documents', 'reviewer_notes')
    # ### end Alembic commands ###
